const testRouter = {
  route: null,
  name: null,
  title: '测试结果',
  type: 'folder',
  icon: 'iconfont icon-result',
  filePath: 'views/test/',
  order: 5,
  inNav: true,
  children: [
    {
      title: '运行记录',
      type: 'view',
      name: 'testRecord',
      route: '/test/record',
      filePath: 'views/test/record/RecordList',
      inNav: true,
      icon: 'iconfont icon-executeRecord',
      keepAlive: true,
      permission: ['运行记录'],
    },
    {
      title: '运行详情',
      type: 'view',
      name: 'testDetail',
      route: '/test/detail',
      filePath: 'views/test/detail/TestDetail.vue',
      inNav: true,
      icon: 'iconfont icon-executeDetail',
      keepAlive: true,
      permission: ['运行详情'],
    },
    {
      title: '用例日志',
      type: 'view',
      name: 'caseLogs',
      route: '/test/log',
      filePath: 'views/test/log/LogList.vue',
      inNav: true,
      icon: 'iconfont icon-caseLog',
      keepAlive: true,
      permission: ['用例日志列表'],
    },
  ],
}

export default testRouter
